### ISSUE TITLE
Missing class constants Application::ROUTING_MIDDLEWARE and Application::DISPATCH_MIDDLEWARE

### ISSUE THREAD

**Issue by boesing** [zendframework/zend-expressive-migration#15]
If the migration for the interop-middlewares is running, I'll receive the following exception:

```
> expressive 'migrate:interop-middleware' '--src' 'src'
PHP Fatal error:  Uncaught Error: Undefined class constant 'ROUTING_MIDDLEWARE' in config/pipeline.php:39
Stack trace:
#0 vendor/zendframework/zend-config-aggregator/src/PhpFileProvider.php(35): include()
#1 vendor/zendframework/zend-config-aggregator/src/ConfigAggregator.php(224): Zend\ConfigAggregator\PhpFileProvider->__invoke()
#2 vendor/zendframework/zend-config-aggregator/src/ConfigAggregator.php(73): Zend\ConfigAggregator\ConfigAggregator->loadConfigFromProviders(Array)
#3 config/config.php(42): Zend\ConfigAggregator\ConfigAggregator->__construct(Array, 'data/config-cac...')
#4 config/container.php(7): require('...')
#5 vendor/zendframework/zend-expressive-tooling/src/ConfigAndContainerTrait.php(28): require('...')
#6 config/pipeline.php on line 39
Script expressive handling the expressive event returned with error code 25
```

Migration Informations:
https://docs.zendframework.com/zend-expressive/v2/reference/migration-to-v2-2/#routing-and-dispatch-constants

I was migrating from `zendframework/zend-expressive` v2.1.0
```Detected expressive in version 2.1.0```

**Comment by michalbundyra** [comment]
As noted in #15 we are not supporting confg-driven middleware pipelnie and this looks like an issue with that. I've tried to add the migration script for it, but it's to complex and we are not gonna support all cases anyway. Closing as "wontfix".

**Comment by boesing** [comment]
Thanks for taking the time to evaluate the problem.
